### PR TITLE
remove all rejectUnauthorized: false request options.

### PR DESCRIPTION
**Pull request by dknochen**
the option "rejectUnauthorized: false" prevents using globalAgent

### CODE REVIEW

**Comment by dknochen** [comment]
@wcandillon this will allow us to use global-tunnel

**Comment by wcandillon** [comment]
@dknochen We need to update swagger-js-codegen for this: https://github.com/wcandillon/swagger-js-codegen/blob/master/templates/node-request.mustache#L7
What is the impact of this change? That we cannot use HTTPs anymore right?

**Comment by dknochen** [comment]
@wcandillon yes, swagger-code-gen should be updated then. We can still use https without this option. Valid ssl certificates should always work. I guess it was a workaround for when there was no propper certificate in place? This option should never be used in production actually.

**Comment by wcandillon** [comment]
cool :)

**Comment by wcandillon** [comment]
@dknochen The package is at 0.1.7 on npm but the package.json on master is 0.1.6. Did you publish the stuff manually somehow?

**Comment by dknochen** [comment]
@wcandillon I didn't publish it on npm. Didn't know that I can do that?

**Comment by wcandillon** [comment]
Yes I figured. Weird stuff.

**Pull request merged**
